[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[general]
# Caminho correto do seu JSON no repositório
GOOGLE_APPLICATION_CREDENTIALS = ".devcontainer/monitoramento-cigarrinha-firebase-adminsdk-fbsvc-bc3a7a07a7.json"
